#[[
from https://gitlab.com/jhamberg/cmake-examples

Copyright (c) 2901 Jonathan Hamberg

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
]]

function(InLangSetup)
	if (NOT EXISTS ${CMAKE_BINARY_DIR}/InLang)
		file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/InLang)
	endif ()
	
	if (NOT EXISTS ${CMAKE_BINARY_DIR}/InLang/placeholder.cpp)
		file(WRITE ${CMAKE_BINARY_DIR}/InLang/placeholder.cpp "")
	endif ()
	
	add_subdirectory(language-strings EXCLUDE_FROM_ALL)
	link_libraries(language-strings)
	
	add_library(InLang ${CMAKE_BINARY_DIR}/InLang/placeholder.cpp)
	target_include_directories(InLang PUBLIC ${CMAKE_BINARY_DIR}/InLang)
endfunction()

function(MakeInLang)
	GenInLang(var)
	target_sources(InLang PUBLIC ${var})
endfunction()

function(GenInLang inLang_cpp)
	set(file "${CMAKE_SOURCE_DIR}/language-strings/sources/strings.cpp")
	#message("${file}")
	
	# read and convert to list https://cmake.cmake.narkive.com/hNRFK8tA/reading-in-a-file-and-splitting-by-line#post3
	FILE(READ ${file} contents)
	STRING(REGEX REPLACE ";" "\\\\;" contents "${contents}")
	STRING(REGEX REPLACE "\n" ";" contents "${contents}")
	
	# cpp
	set(outfile "${CMAKE_BINARY_DIR}/InLang/inLang.cpp")
	message("Generating ${outfile}")
	
	file(WRITE "${outfile}"
		"// This code was generated by CMake script.\n"
		"//\n"
		"// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.\n"
		"#include \"inLang.hpp\"\n"
		"\n"
	)
	
	foreach(line ${contents})
		# get lines starting with std::string
		string(REGEX MATCH ".*(std::string )" string "${line}")
		string(COMPARE EQUAL "${string}" "std::string " isStdString)
		if (${isStdString})
			# isolate variable name
			string(REGEX MATCH "( ).*" var "${line}")
			string(STRIP "${var}" var)
			string(REGEX MATCH "^[^ ]*" var "${var}")
			string(STRIP "${var}" var)
			
			file(APPEND "${outfile}"
				"std::string inLang${var} = \"${var}\";\n"
			)
		endif()
	endforeach()
	
	file(APPEND "${outfile}"
		"\n"
		"void fillLangVecs(std::vector<std::string*>* inLangVec, std::vector<std::string*>* LangVec) {\n"
	)
	
	# inLangVec
	foreach(line ${contents})
		# get lines starting with std::string
		string(REGEX MATCH ".*(std::string )" string "${line}")
		string(COMPARE EQUAL "${string}" "std::string " isStdString)
		if (${isStdString})
			# isolate variable name
			string(REGEX MATCH "( ).*" var "${line}")
			string(STRIP "${var}" var)
			string(REGEX MATCH "^[^ ]*" var "${var}")
			string(STRIP "${var}" var)
			
			file(APPEND "${outfile}"
				"	inLangVec->push_back(&inLang${var});\n"
			)
		endif()
	endforeach()

	file(APPEND "${outfile}"
		"	\n"
	)

	# LangVec
	foreach(line ${contents})
		# get lines starting with std::string
		string(REGEX MATCH ".*(std::string )" string "${line}")
		string(COMPARE EQUAL "${string}" "std::string " isStdString)
		if (${isStdString})
			# isolate variable name
			string(REGEX MATCH "( ).*" var "${line}")
			string(STRIP "${var}" var)
			string(REGEX MATCH "^[^ ]*" var "${var}")
			string(STRIP "${var}" var)
			
			file(APPEND "${outfile}"
				"	LangVec->push_back(&${var});\n"
			)
		endif()
	endforeach()
	
	file(APPEND "${outfile}"
		"}\n"
	)
	
	# hpp
	set(outfile "${CMAKE_BINARY_DIR}/InLang/inLang.hpp")
	message("Generating ${outfile}")
	
	file(WRITE "${outfile}"
		"// This code was generated by CMake script.\n"
		"//\n"
		"// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.\n"
		"#ifndef INLANG_H\n"
		"#define INLANG_H\n"
		"\n"
		"#include <filesystem>\n"
		"#include <vector>\n"
		"\n"
		"#include <strings.hpp>\n"
		"\n"
	)
	
	foreach(line ${contents})
		# get lines starting with std::string
		string(REGEX MATCH ".*(std::string )" string "${line}")
		string(COMPARE EQUAL "${string}" "std::string " isStdString)
		if (${isStdString})
			# isolate variable name
			string(REGEX MATCH "( ).*" var "${line}")
			string(STRIP "${var}" var)
			string(REGEX MATCH "^[^ ]*" var "${var}")
			string(STRIP "${var}" var)
			
			file(APPEND "${outfile}"
				"extern std::string inLang${var};\n"
			)
		endif()
	endforeach()
	
	file(APPEND "${outfile}"
		"\n"
		"void fillLangVecs(std::vector<std::string*>* inLangVec, std::vector<std::string*>* LangVec);\n"
		"\n"
		"#endif // INLANG_H\n"
	)
	
	# txt
	set(outfile "${CMAKE_CURRENT_SOURCE_DIR}/VidInjector9000Resources/language/English/Language.txt")
	message("Generating ${outfile}")
	
	FILE(READ "${file}" contents)
	
	# remove header
	STRING(REPLACE "#include \"strings.hpp\"\n\n" "" contents "${contents}")
	
	# remove all "std::string "
	STRING(REPLACE "std::string " "" contents "${contents}")
	
	# replace stuff with unit separators
	string(ASCII 31 US)
	STRING(REPLACE " = \"" "=${US}" contents "${contents}")
	STRING(REPLACE "\";" "${US}" contents "${contents}")
	
	# fix other stuff from the strings
	STRING(REPLACE "\\\"" "\"" contents "${contents}")
	STRING(REPLACE "\\n" "\n" contents "${contents}")
	#message("${contents}")
	
	file(WRITE "${outfile}"
		"${contents}"
	)
	
	set(${inLang_cpp} ${CMAKE_BINARY_DIR}/InLang/inLang.cpp PARENT_SCOPE)
endfunction()
