#pragma once

#include <string>

//stuff you dont change
extern std::string Version;
extern std::string LogoASCII;
extern std::string HArg;
extern std::string HArgShort;
extern std::string NArg;
extern std::string NArgShort;
extern std::string SpArg;
extern std::string SpArgShort;
extern std::string PpArg;
extern std::string PpArgShort;
extern std::string ArArg;
extern std::string ArArgShort;
extern std::string SrArg;
extern std::string SrArgShort;
extern std::string BcArg;
extern std::string BcArgShort;
extern std::string EcArg;
extern std::string EcArgShort;

extern std::string Languagedir;

//vi9p file stuff
extern std::string resourcesPath;
extern std::string VI9PVER;
extern std::string StrVerParam;
extern std::string IntMultiParam;
extern std::string StrBannerParam;
extern std::string StrIconParam;
extern std::string IntIconBorderParam;
extern std::string StrSNameParam;
extern std::string StrLNameParam;
extern std::string StrPublisherParam;
extern std::string IntCopycheckParam;
extern std::string StrCopyrightParam;
extern std::string IntFFrewindParam;
extern std::string IntFadeOptParam;
extern std::string IntRowsParam;
extern std::string StrPTitleParam;
extern std::string StrMoflexParam;
extern std::string StrMBannerParam;
extern std::string IntPreIndexParam;

//stuff you change
extern std::string ProgramName;
extern std::string ByMeText;
extern std::string InfoText;
extern std::string UsageText;
extern std::string ExampleText;
extern std::string ArgumentText;
//extern std::string ParametersText;
//extern std::string InformationText;
//extern std::string HelpInfoText;
//extern std::string Help2InfoText;
extern std::string NewInfoText;
extern std::string SetPInfoText;
extern std::string PrintPInfoText;
extern std::string AddRInfoText;
extern std::string SubRInfoText;
extern std::string BuildCInfoText;
extern std::string BuildC2InfoText;
extern std::string ExCInfoText;
extern std::string ExC2InfoText;
extern std::string InVi9pFile;
extern std::string InCiaFile;
extern std::string OutVi9pFile;
extern std::string OutCiaFile;
extern std::string OutDir;
extern std::string SeedFile;
extern std::string SeedNotFound;
extern std::string number;
extern std::string NewValueText;
extern std::string UniqueIDText;
extern std::string AppTitleText;
extern std::string ProdCodeLatt;
extern std::string OutDirText;
extern std::string ErrorText;
extern std::string UnknownArgText;
extern std::string BadValue;
extern std::string BadVersion;
extern std::string SupportedVersion;
extern std::string BeANumber;
extern std::string MissingVariableError;
extern std::string FailedToFindVar;
extern std::string FailedToFindPath;
extern std::string FailedToFindFile;
extern std::string FailedToReadFile;
extern std::string FailedToCopyFile;
extern std::string FailedToCreateFile;
extern std::string FailedToConvertImage;
extern std::string FailedToReadExHeader;
extern std::string ValueNoChange;
extern std::string noMoreThan27;
extern std::string ParametersLoaded;
extern std::string SuccessfullyLoaded;
extern std::string FailedToLoad;
extern std::string ValidStillLoaded;
extern std::string CreatingFile;
extern std::string CopyingMoflex;
extern std::string MoflexError;
extern std::string ProductCodetext;
