#pragma once

#include "widgets.hpp"

class Language {
	public:
	static std::vector<std::string> LanguageFiles;
};

bool loadLanguage(std::string LangPath);//generated by the helper thing
void applyLanguage(InitWidgets* wid);
