#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#include "../src/form1.h"
#include <xtd/startup.h>

startup_(VidInjector9002::form1);
#pragma endregion
