# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# I'm dumb so i'll just use this but make multiple jobs to build for each target platforms
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  linux:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Init Submodules
      run: git submodule update --init --recursive

    - name: Run deploy script
      working-directory: ${{github.workspace}}
      run: |
           chmod +x deploy.sh
           ./deploy.sh
           ls out

  macOS:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Init Submodules
      run: git submodule update --init --recursive

    - name: Run deploy script
      working-directory: ${{github.workspace}}
      run: |
           chmod +x deploy.sh
           ./deploy.sh
           ls out

  macOS-intel:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@v4

    - name: Init Submodules
      run: git submodule update --init --recursive

    - name: Run deploy script
      working-directory: ${{github.workspace}}
      run: |
           chmod +x deploy.sh
           ./deploy.sh
           ls out

  windows:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Init Submodules
      run: git submodule update --init --recursive

    - name: Run deploy script
      working-directory: ${{github.workspace}}
      run: |
           ./deploy.bat
           dir out
