name: Run Script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import sys
            import shutil
            import subprocess

            if sys.platform == "win32" or sys.platform == "cygwin":
                bin = "VidInjector9001.exe"
            else:
                bin = "VidInjector9001"
            cpp = "c++17"

            if os.path.exists(bin):
                os.remove(bin)

            if not os.path.exists("obj/Debug"):
                os.makedirs("obj/Debug")

            files = ""
            for s in os.listdir("."):
                if s.find(".c") != -1:
                    print(s)
                    if os.path.exists("obj/Debug/" + s.rsplit('.', 1)[0] + ".o"):
                        ofile = os.path.getmtime("obj/Debug/" + s.rsplit('.', 1)[0] + ".o")
                    else:
                        ofile = 0.0
                    if os.path.exists(s):
                        cfile = os.path.getmtime(s)
                    else:
                        cfile = 1.0
                    if(cfile >= ofile):
                        if os.path.exists("obj/Debug/" + s.rsplit('.', 1)[0] + ".o"):
                            os.remove("obj/Debug/" + s.rsplit('.', 1)[0] + ".o")
                        subprocess.call("g++ -Wall -c -g " + s + " -std=" + cpp + " -o obj/Debug/" + s.rsplit('.', 1)[0] + ".o")
                    files += "obj/Debug/" + s.rsplit('.', 1)[0] + ".o"

            subprocess.call("g++ -static -static-libgcc -static-libstdc++ -o \"" + bin + "\" " + files)
